# Generated by Django 5.2.1 on 2025-06-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.IntegerField()),
                ('is_filled', models.BooleanField(default=False)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spaces', to='home.aisle')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('storage_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='home.storagespace')),
            ],
        ),
    ]
