# Generated by Django 5.2.1 on 2025-06-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aisle_storagespace_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('storage_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='home.storagespace')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
