# Generated by Django 5.2.1 on 2025-06-03 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisle',
            name='storage_space',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aisle',
            name='storage_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.storagespace'),
        ),
    ]
