# Generated by Django 5.2.1 on 2025-06-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aisle_storage_space_alter_aisle_storage_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisle',
            name='storage_space',
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='home.storagespace'),
        ),
    ]
