# Generated by Django 5.2.1 on 2025-06-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_aisle_storage_space_alter_item_storage_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storage_space',
        ),
        migrations.AddField(
            model_name='item',
            name='aisle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.aisle'),
            preserve_default=False,
        ),
    ]
