# Generated by Django 5.2.1 on 2025-06-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='home.storagespace'),
        ),
    ]
